server:
  port: 8690
spring:
  #recon influxdb
  influx:
    database: caspian_feed
    url: http://localhost:8086
    user:
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms_feeds?autoReconnect=true&useSSL=false
    username: root
    password: pass1234
cep:
  host: https://cep:8446/
  api-key: a2b877e4-074b-40d2-aae4-80957613cf63
  secret: q0FY+zexijMT56Qe2t0PH59wqb89JuJZazWVr4dXJogQAHeMCHV587O/N0/ppqbTF/i3PUjDe642UkhUsIIISA==
platform:
  host: https://oat.digitalmarkets.trade
  api-key: 26026d7e-85a8-4ef5-b135-2b9214b61d7e
  secret: chBAnHg7xKz1dReTlAhdJLoGg4YdiAxi9fmOYDK2/w2KSHxG15aq6/TTAVrvghwxBqQNnOqIQuJYjNDFQYFznw==
caspian:
  connection-url: https://api.caspian.tech
  api-key: Ag3okDk51JqqT8Ly
  secret: SrM3Pi4MriMdvnlffI70O7qhv1qExIPZ
  path-name: pms-demo
#health monitoring
management:
  metrics:
    export:
      influx:
        enabled: true
        uri: http://metrics:8086
        db: caspian
        user-name: caspian_rw
        password: xxxxxx
        auto-create-db: false
